### ISSUE TITLE
Every colcon package now prints an error at bootstrap time

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-python-setup-py#7]
This happens after the first build, at the beginning of the second build.

```
ERROR:colcon.colcon_core.package_identification:Exception in package identification extension 'python_setup_py' in '/home/mikael/work/ros2/colcon/src/colcon-argcomplete': setup() function invoked without the keyword argument 'name'
Traceback (most recent call last):
  File "/home/mikael/work/ros2/colcon/install/colcon-core/lib/python3.5/site-packages/colcon_core/package_identification/__init__.py", line 135, in _identify
    retval = extension.identify(desc2)
  File "/home/mikael/work/ros2/colcon/install/colcon-python-setup-py/lib/python3.5/site-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 42, in identify
    data = extract_data(**kwargs)
  File "/home/mikael/work/ros2/colcon/install/colcon-python-setup-py/lib/python3.5/site-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 158, in extract_data
    "setup() function invoked without the keyword argument 'name'")
RuntimeError: setup() function invoked without the keyword argument 'name'
```

**Comment by dirk-thomas** [comment]
This should be fixed by #3.
